-- MySQL Script generated by MySQL Workbench
-- jue 20 dic 2018 10:57:20 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reporteador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reporteador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reporteador` ;
USE `reporteador` ;

-- -----------------------------------------------------
-- Table `reporteador`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporteador`.`grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `alias` VARCHAR(50) NULL,
  `rfc` VARCHAR(13) NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporteador`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporteador`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `email` VARCHAR(50) NULL,
  `usuario` VARCHAR(50) NULL,
  `pass` VARCHAR(20) NULL,
  `tipo_usuario` VARCHAR(2) NULL,
  `fk_grupou` INT NULL,
  PRIMARY KEY (`idusuarios`),
  CONSTRAINT `fk_grupou`
    FOREIGN KEY (`fk_grupou`)
    REFERENCES `reporteador`.`grupo` (`idgrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporteador`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporteador`.`equipos` (
  `idequipos` INT NOT NULL AUTO_INCREMENT,
  `nombre_host` VARCHAR(50) NULL,
  `dns` VARCHAR(15) NULL,
  `descripcion` VARCHAR(255) NULL,
  `fk_grupo` INT NULL,
  PRIMARY KEY (`idequipos`),
  CONSTRAINT `fk_grupo`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `reporteador`.`grupo` (`idgrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporteador`.`lada`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `reporteador`.`contactos`


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
